FROM almalinux:9
#RUN useradd expense
#USER expense
#RUN mkdir /workdir
#WORKDIR /workdir
ARG user1=someuser
RUN echo "hello ${user1}"
CMD ["sleep","100"]
#ENTRYPOINT ["ping"]
#CMD ["google.com"]
#EXPOSE 80
#ENV project="devops" \
    #name="gali"
#RUN dnf install nginx -y
#RUN rm -f /usr/share/nginx/html/index.html
#COPY index.html /usr/share/nginx/html/index.html
#CMD ["nginx", "-g", "daemon off;"]
#LABEL project="devops" \
      #name="gali"