FROM almalinux:9
CMD ["ping", "google.com"]
#EXPOSE 80
#ENV project="devops" \
    #name="gali"
#RUN dnf install nginx -y
#RUN rm -f /usr/share/nginx/html/index.html
#COPY index.html /usr/share/nginx/html/index.html
#CMD ["nginx", "-g", "daemon off;"]
#LABEL project="devops" \
      #name="gali"