apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "printenv && sleep infinity"]
      image: busybox:latest
      envFrom:
        - configMapRef:
            name: myconfigmap
        - secretRef:
            name: my-secret