apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: screte-reader        # Add this
  namespace: expense
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-pods       # Add this
  namespace: expense
subjects:
- kind: ServiceAccount
  name: aws-service-account
  namespace: expense
roleRef:
  kind: Role
  name: screte-reader
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
  serviceAccountName: aws-service-account
  volumes:
  - name: secrets
    emptyDir: {}
  initContainers:
  - name: fetch-secrets
    image: amazon/aws-cli:latest
    command: ["sh", "-c"]
    args:
    - |
      aws secretsmanager get-secret-value \
        --secret-id mysqlrds \
        --region us-east-1 \
        --query SecretString \
        --output text > /secrets/credentials.json
    volumeMounts:
    - name: secrets
      mountPath: /secrets
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: /mnt/secrets
      readOnly: true

