apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql-sa
  namespace: mssql
  labels:
    app: mssql
  annotations:
    # IRSA - replace with your actual role ARN after running eksctl create iamserviceaccount
    eks.amazonaws.com/role-arn: arn:aws:iam::856678556116:role/mssql-secrets-role
