apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: expense
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: manjudbadevops/mysql:1.0.0
        