apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: manjudbadevops/mysql:1.0.0
          volumeMounts:
            - name: www
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: www
        namespace: expense
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp3-storage"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: expense
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306