apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mssql.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mssql.labels" . | nindent 4 }}
data:
  mssql.conf: |
    [sqlagent]
    enabled = {{ .Values.mssql.agentEnabled }}

    [memory]
    memorylimitmb = {{ .Values.mssql.memoryLimitMB }}

    [network]
    tlsprotocols = {{ .Values.config.tlsProtocols }}
    forceencryption = {{ .Values.config.forceEncryption }}

    [telemetry]
    customerfeedback = {{ .Values.config.telemetry }}

    [traceflag]
    {{- range $i, $flag := .Values.config.traceFlags }}
    traceflag{{ $i }} = {{ $flag }}
    {{- end }}
