apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hardware
                operator: In
                values:
                  - gcp
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "hardware"
      operator: "Equal"
      value: "gcp"
      effect: "NoSchedule"
