apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"